[project]
name = "multi-modal-ml-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.5.0",
    "openai>=2.11.0",
    "pillow>=12.0.0",
    "regex>=2025.11.3",
]
